name: Gerar APK Flet

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Configurar Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Instalar Flet e Dependências
        run: |
          python -m pip install --upgrade pip
          pip install flet

      - name: Compilar APK
        run: flet build apk

      - name: Disponibilizar APK para Download
        uses: actions/upload-artifact@v4
        with:
          name: AppClinica-Victor
          path: build/apk/**/*.apk
